services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/app/migrations
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  db_data:
