services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
